### ISSUE TITLE
Windows 10 explorer crash

### ISSUE THREAD

**Issue by GoldenFlamingo** [dedmen/PboExplorer#9]
Windows explorer crashes when trying to open an obfuscated pbo

**Comment by dedmen** [comment]
Please send me the obfuscated pbo. I need to reproduce the issue.

**Comment by Payns13** [comment]
> Please send me the obfuscated pbo. I need to reproduce the issue.

https://we.tl/t-B7y2MudZDC

**Comment by dedmen** [comment]
Interesting. On first open, I also crashed. But the crash didn't really make sense.
Then explorer restarted, and on second open everything is fine. I also cannot reproduce that crash after multiple restarts.

I can even browse into subfolders just fine, though of course most of them are filled with garbage that I can't do much about.


The .paa preview is funny. Most files are simply black because they are garbage.
But you can somewhat easily find valid paa files, by looking at which ones generate a thumbnail :D 
![WindowsSandboxClient_2024-07-23_13-59-49](https://github.com/user-attachments/assets/eef0c848-00ad-4125-a044-77903c1e7917)

**Comment by dedmen** [comment]
Nevermind I see what happened when I crashed. A race condition. 
Fixed next update
